;* Yggdrasil (TM) Core Operating System (MCS-80/85): Character Library
;* Copyright (CF) DeRemee Systems, IXE Electronics LLC
;* Portions copyright IXE Electronics LLC, Republic Robotics, FemtoLaunch, FemtoSat, FemtoTrack, Weland
;* This work is made available under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
;* To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/4.0/.


PUBLIC	LCHARASC2INT
;CONVERTS THE ASCII CHARACTER IN A TO AN INTEGER
;ON ENTRY:
;	A = ASCII CHARACTER
;ON RETURN:
;	CF = 0 IF CHARACTER IS A NUMBER
;			A = INTEGER VALUE
;	CF = 1 IF CHARACTER IS NOT A NUMBER
;			A = 0000
				;CHECK FOR GREATER THAN "9"
LCHARASC2INT:	CPI		03AH
				JNC		LCHARASC2INTA
				;CONVERT & CHECK FOR LESS THAN "0"
				SUI		030H
				JC		LCHARASC2INTA
				;
				STC
				CMC
				RET
LCHARASC2INTA:	XRA		A
				STC
				RET
	
	
PUBLIC	LCHARHEX2INT
;CONVERTS THE HEX CHARACTER IN A TO AN INTEGER
;ON ENTRY:
;	A = VALUE
;ON RETURN:
;	CF = 0 IF CHARACTER IS HEX
;			A = INTEGER VALUE
;	CF = 1 IF CHARACTER IS NOT HEX
;			A = 0000
				;CHECK FOR LESS THAN "0"
LCHARHEX2INT:	SUI		030H
				JC		LCHARHEX2INTD
				;CHECK FOR GREATER THAN "9"
				CPI		00AH
				JNC		LCHARHEX2INTB
LCHARHEX2INTA:	CMC
				RET
				;CHECK FOR LESS THAN "A"
LCHARHEX2INTB:	SUI		007H
				JC		LCHARHEX2INTD
				;CHECK FOR GREATER THAN "F" OR "f"
LCHARHEX2INTC:	CPI		00AH
				JC		LCHARHEX2INTD
				CPI		010H
				JC		LCHARHEX2INTA
				;CHECK FOR LESS THAN "a"
				SUI		020H
				JNC		LCHARHEX2INTC
LCHARHEX2INTD:	XRA		A
				STC
				RET


PUBLIC	LCHAR2LOWER
;CONVERTS AN UPPERCASE LETTER TO A LOWERCASE LETTER
;ON ENTRY:
;	A = CHARACTER
;ON RETURN:
;	CF = 0 IF CHARACTER WAS UPPERCASE
;		A = CONVERTED VALUE
;	CF = 1 IF CHARACTER WAS NOT UPPERCASE
;		A = VALUE ON ENTRY
				;CHECK FOR LESS THAN "A"
LCHAR2LOWER:	CPI		041H
				JC		LCHAR2LOWERB
				;CHECK FOR GREATER THAN "Z"
				CPI		05BH
				JNC		LCHAR2LOWERA
				;CONVERT TO LOWERCASE
				ADI		020H
				RET
LCHAR2LOWERA:	STC
LCHAR2LOWERB:	RET


PUBLIC	LCHAR2UPPER
;CONVERTS A LOWERCASE LETTER TO AN UPPERCASE LETTER
;ON ENTRY:
;	A = CHARACTER
;ON RETURN:
;	CF = 0 IF CHARACTER WAS LOWERCASE
;		A = CONVERTED VALUE
;	CF = 1 IF CHARACTER WAS NOT LOWERCASE
;		A = VALUE ON ENTRY
				;CHECK FOR LESS THAN "a"
LCHAR2UPPER:	CPI		061H
				JC		LCHAR2UPPERB
				;CHECK FOR GREATER THAN "z"
				CPI		07BH
				JNC		LCHAR2UPPERA
				;CONVERT TO UPPERCASE
				SUI		020H
				RET
LCHAR2UPPERA:	STC
LCHAR2UPPERB:	RET


PUBLIC	LCHARISARITH
;RETURNS TRUE IF VALUE IS AN ARITHMETIC OPERATOR
;ON ENTRY:
;	A = VALUE
;ON RETURN:
;	A = VALUE ON ENTRY
;	CF = 0 IF VALUE IS NOT AN ARITHMETIC OPERATOR
;	CF = 1 IF VALUE IS AN ARITHMETIC OPERATOR
				;CHECK FOR FACTORAL "!"
LCHARISARITH:	CPI		021H
				JZ		LCHARISARITHA
				;CHECK FOR MODULO "%"
				CPI		025H
				JZ		LCHARISARITHA
				;CHECK FOR MULTIPLICATION "*"
				CPI		02AH
				JZ		LCHARISARITHA
				;CHECK FOR ADDITION "+"
				CPI		02BH
				JZ		LCHARISARITHA
				;CHECK FOR SUBTRACTION "-"
				CPI		02DH
				JZ		LCHARISARITHA
				;CHECK FOR DIVISION "/"
				CPI		02FH
				JZ		LCHARISARITHA
				;CHECK FOR EQUALS "="
				CPI		03DH
				JZ		LCHARISARITHA
				;CHECK FOR EXPONENT "^"
				CPI		05EH
				JNZ		LCHARISARITHB
LCHARISARITHA:	STC
				RET
LCHARISARITHB:	STC
				CMC
				RET


PUBLIC	LCHARISBRACC
;RETURNS TRUE IF VALUE IS A CLOSING BRACKET
;ON ENTRY:
;	A = VALUE
;ON RETURN:
;	A = VALUE ON ENTRY
;	CF = 0 IF VALUE IS NOT A CLOSING BRACKET
;	CF = 1 IF VALUE IS AN A CLOSING BRACKET
				;CHECK FOR "("
LCHARISBRACC:	CPI		0028H
				JZ		LCHARISBRACCA
				;CHECK FOR "["
				CPI		005BH
				JZ		LCHARISBRACCA
				;CHECK FOR "{"
				CPI		007BH
				JNZ		LCHARISBRACCB
LCHARISBRACCA:	STC
				RET
LCHARISBRACCB:	STC
				CMC
				RET


PUBLIC	LCHARISBRACO
;RETURNS TRUE IF VALUE IS AN OPENING BRACKET
;ON ENTRY:
;	A = VALUE
;ON RETURN:
;	A = VALUE ON ENTRY
;	CF = 0 IF VALUE IS NOT AN OPENING BRACKET
;	CF = 1 IF VALUE IS AN AN OPENING BRACKET
				;CHECK FOR ")"
LCHARISBRACO:	CPI		0029H
				JZ		LCHARISBRACOA
				;CHECK FOR "]"
				CPI		005DH
				JZ		LCHARISBRACOA
				;CHECK FOR "}"
				CPI		007DH
				JNZ		LCHARISBRACOB
LCHARISBRACOA:	STC
				RET
LCHARISBRACOB:	STC
				CMC
				RET


PUBLIC	LCHARISHEX
;RETURNS TRUE IF VALUE IS A HEX CHARACTER
;ON ENTRY:
;	A = VALUE
;ON RETURN:
;	A = VALUE ON ENTRY
;	CF = 0 IF VALUE IS NOT A HEX CHARACTER
;	CF = 1 IF VALUE IS A HEX CHARACTER
LCHARISHEX:
	;CHECK FOR LESS THAN "0"
	CPI		A, 0030
	JC		LCHARISHEXA
	;CHECK FOR GREATER THAN "9"
	CPI		A, 003A
	JC		LCHARISHEXB
	;CHECK FOR LESS THAN "A"
	CPI		A, 0041
	JC		LCHARISHEXA
	;CHECK FOR GREATER THAN "F"
	CPI		A, 0047
	JC		LCHARISHEXB
LCHARISHEXA:
	CLC
LCHARISHEXB:
	RET


PUBLIC	LCHARISLETTER
;RETURNS TRUE IF VALUE IS A LETTER
;ON ENTRY:
;	A = VALUE
;ON RETURN:
;	A = VALUE ON ENTRY
;	CF = 0 IF VALUE IS NOT A LETTER
;	CF = 1 IF VALUE IS A LETTER
LCHARISLETTER:
	;CHECK FOR LESS THAN "A"
	CPI		A, 0041
	JC		LCHARISLETTERA
	;CHECK FOR GREATER THAN "Z"
	CPI		A, 005B
	JNC		LCHARISLETTERB
	;CHECK FOR LESS THAN "a"
	CPI		A, 0061
	JC		LCHARISLETTERA
	;CHECK FOR GREATER THAN "z"
	CPI		A, 007B
	JNC		LCHARISLETTERB
	RET
LCHARISLETTERA:
	CLC
LCHARISLETTERB:
	RET


PUBLIC	LCHARISLOGIC
;RETURNS TRUE IF VALUE IS A LOGICAL OPERATOR
;ON ENTRY:
;	A = VALUE
;ON RETURN:
;	A = VALUE ON ENTRY
;	CF = 0 IF VALUE IS NOT A LOGICAL OPERATOR
;	CF = 1 IF VALUE IS AN A LOGICAL OPERATOR
LCHARISLOGIC:
	;CHECK FOR NOT "!"
	CPI		A, 0021
	JZ		LCHARISLOGICA
	;CHECK FOR AND "&"
	CPI		A, 0026
	JZ		LCHARISLOGICA
	;CHECK FOR XOR "^"
	CPI		A, 005E
	JZ		LCHARISLOGICA
	;CHECK FOR OR "|"
	CPI		A, 007C
	JNZ		LCHARISLOGICB
LCHARISLOGICA:
	STC
	RET
LCHARISLOGICB:
	CLC
	RET


PUBLIC	LCHARISNUM
;RETURNS TRUE IF VALUE IS A NUMBER
;ON ENTRY:
;	A = VALUE
;ON RETURN:
;	A = VALUE ON ENTRY
;	CF = 0 IF VALUE IS NOT A NUMBER
;	CF = 1 IF VALUE IS A NUMBER
LCHARISNUM:
	;CHECK FOR LESS THAN "0"
	CPI		A, 0030
	JC		LCHARISNUMA
	;CHECK FOR GREATER THAN "9"
	CPI		A, 003A
	JNC		LCHARISNUMB
	RET
LCHARISNUMA:
	CLC
LCHARISNUMB:
	RET

	
PUBLIC	LCHARISPUNCT
;RETURNS TRUE IF VALUE IS PUNCTUATION
;ON ENTRY:
;	A = VALUE
;ON RETURN:
;	A = VALUE ON ENTRY
;	CF = 0 IF VALUE IS NOT PUNCTUATION
;	CF = 1 IF VALUE IS PUNCTUATION
LCHARISPUNCT:
	;CHECK FOR "!"
	CPI		A, 0021
	JZ		LCHARISPUNCTA
	;CHECK FOR "."
	CPI		A, 002E
	JZ		LCHARISPUNCTA
	;CHECK FOR "?"
	CPI		A, 003F
	JNZ		LCHARISPUNCTB
LCHARISPUNCTA:
	STC
	RET
LCHARISPUNCTB:
	CLC
	RET


PUBLIC	LCHARISREL
;RETURNS TRUE IF VALUE IS A RELATIONAL OPERATOR
;ON ENTRY:
;	A = VALUE
;ON RETURN:
;	A = VALUE ON ENTRY
;	CF = 0 IF VALUE IS NOT A RELATIONAL OPERATOR
;	CF = 1 IF VALUE IS A RELATIONAL OPERATOR
LCHARISREL:
	;CHECK FOR LESS THAN "<"
	CPI		A, 003C
	JC		LCHARISRELA
	;CHECK FOR GREATER THAN ">"
	CPI		A, 003F
	JNC		LCHARISRELB
	RET
LCHARISRELA:
	CLC
LCHARISRELB:
	RET
