;* Yggdrasil (TM) Core Operating System (MCS-51): Integer Library Return Codes
;* Copyright (C) DeRemee Systems, IXE Electronics LLC
;* Portions copyright IXE Electronics LLC, Republic Robotics, FemtoLaunch, FemtoSat, FemtoTrack, Weland
;* This work is made available under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
;* To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/4.0/.

INT_ERR_RANGE       EQU	0x01
INT_ERR_NOT_NUMBER  EQU	0x02
