;* Yggdrasil (TM) Core Operating System (IA-32): Character Library
;* Copyright (C) DeRemee Systems, IXE Electronics LLC
;* Portions copyright IXE Electronics LLC, Republic Robotics, FemtoLaunch, FemtoSat, FemtoTrack, Weland
;* This work is made available under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
;* To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/4.0/.


;PACKS FOUR CHARACTERS INTO A SINGLE 32-BIT WORD
;ASSUMES EACH CHARACTER IS STORED IN THE LEAST
;SIGNIFICANT BYTE OF EACH 32-BIT WORD AND THE
;REMAINING BITS WITHIN THE WORD ARE CLEARED
;UNROLLED FOR SPEED
;ON ENTRY:
; DF    = AS REQUIRED
; DS:SI = SOURCE ADDRESS
;ON RETURN:
; DF    = VALUE ON ENTRY
; EAX   = RESULT
; DS:SI = VALUE ON ENTRY +/- 16
LCHARPACK32:
    ;SAVE REGISTERS
    PUSH  EBX
    ;LOAD FIRST CHARACTER
    LODSD
    MOV   EBX, EAX
    ;LOAD SECOND CHARACTER
    LODSD
    ;SHIFT SECOND CHARACTER INTO NEW POSITION
    SHL   EAX, 8
    ;COMBINE FIRST AND SECOND CHARACTERS
    OR    EBX, EAX
    ;LOAD THIRD CHARACTER
    LODSD
    ;SHIFT THIRD CHARACTER INTO NEW POSITION
    SHL   EAX, 16
    ;COMBINE THIRD CHARACTER WITH OTHER CHARACTERS
    OR    EBX, EAX
    ;LOAD FOURTH CHARACTER
    LODSD
    ;SHIFT FOURTH CHARACTER INTO NEW POSITION
    SHL   EAX, 24
    ;COMBINE FOURTH CHARACTER WITH OTHER CHARACTERS
    OR    EBX, EAX
    MOV   EAX, EBX
    ;RESTORE REGISTERS & RETURN
    POP   EBX
    RET
    
    
;UNPACKS FOUR CHARACTERS FROM A SINGLE 32-BIT WORD
;EACH CHARACTER IS STORED IN THE LEAST SIGNIFICANT
;BYTE OF EACH 32-BIT WORD AND THE REMAINING BITS
;WITHIN THE WORD ARE CLEARED
;UNROLLED FOR SPEED & ECX USED FOR MASK TO REDUCE
;IMMEDIATE DATA IN INSTRUCTIONS
;ON ENTRY:
; DF    = AS REQUIRED
; EAX   = VALUE
; ES:DI = DESTINATION ADDRESS
;ON RETURN:
; DF    = VALUE ON ENTRY
; EAX   = VALUE ON ENTRY
; ES:DI = VALUE ON ENTRY +/- 16
LCHARUNPACK32:
    ;SAVE REGISTERS
    PUSH  EBX
    PUSH  ECX
    MOV   EBX, EAX
    ;LOAD MASK
    MOV   ECX, 0x000000FF
    ;MASK OUT BITS 31:8
    MOV   EAX, EBX
    ANL   EAX, ECX
    ;STORE FIRST CHARACTER
    STOSD
    ;SHIFT MASK INTO NEW POSITION
    SHL   ECX, 8
    ;MASK OUT BITS 31:16 & 7:0
    MOV   EAX, EBX
    ANL   EAX, ECX
    ;SHIFT CHARACTER INTO POSITION
    SHR   EAX, 8
    ;STORE SECOND CHARACTER
    STOSD
    ;SHIFT MASK INTO NEW POSITION
    SHL   ECX, 8
    ;MASK OUT BITS 31:24 & 15:0
    MOV   EAX, EBX
    ANL   EAX, ECX
    ;SHIFT CHARACTER INTO POSITION
    SHR   EAX, 16
    ;STORE THIRD CHARACTER
    STOSD
    ;SHIFT MASK INTO NEW POSITION
    SHL   ECX, 8
    ;MASK OUT BITS 23:0
    MOV   EAX, EBX
    ANL   EAX, ECX
    ;SHIFT CHARACTER INTO POSITION
    SHR   EAX, 24
    ;STORE FOURTH CHARACTER
    STOSD
    ;RESTORE REGISTERS & RETURN
    MOV   EAX, EBX
    POP   ECX
    POP   EBX
    RET
